name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Upgrade Ruby version
        bundler-cache: false

    - name: Fix Bundler & Dependencies
      run: |
        gem install rubygems-update -v 3.3.26  # Ensure RubyGems version is compatible with Ruby 3.0.2
        update_rubygems
        gem install bundler -v 2.6.3  # Explicitly install the correct Bundler version
        rm -rf vendor/bundle .bundle Gemfile.lock  # Remove existing dependencies
        bundle install --jobs 4 --retry 3  # Install all gems with parallel processing


    - name: Install additional dependencies
      run: |
        npm install -g mermaid.cli

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
          echo "::set-output name=NO_PUSH::--no-push"
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
        fi
        echo "::set-output name=DEPLOY_BRANCH::gh-pages"

    - name: Deploy website 
      run:  yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }}
                    --src ${{ steps.setup.outputs.SRC_BRANCH }} 
                    --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
